### ISSUE TITLE
The citation always add extra () around the reference inside the theorem environment

### ISSUE THREAD

**Issue by neozhaoliang** [jdutant/statement#11]
![图片](https://github.com/dialoa/statement/assets/23307174/b410c9d3-0cff-477b-b5fc-ae35adb19046)

Hi, when I cite a theorem from a book like 

```
::: {.theorem }
[@Humphreys90 section 5.4]
xxxxx
:::
```

The citation adds an extra pair of `()` around the reference, as the image shows.

Here is my `metadata.yml`: 

https://github.com/neozhaoliang/hyperbolic-sphere-packings-book/blob/main/metadata.yml

**Comment by twsh** [comment]
Would an 'author-in-text' citation work for you? If you write `@Humphreys90 [section 5.4]` you will get 'Humphreys, J. (1990, sec. 5.4)' (in the default bibliography style).

https://pandoc.org/MANUAL.html#citation-syntax

Anyway, the way the filter is written now the statement-info is put in brackets. I think that the plan is that the delimiters for the info can be changed for different styles.

**Comment by neozhaoliang** [comment]
Thank you, I will use the way you suggested!
